baseURL = 'https://rares7.github.io/ejercicio_hugo_clase/'
languageCode = 'es-es'
title = 'Apple Blog'
theme = 'ananke'
[outputs]
  home = ["HTML", "JSON"]

[menu]
  [[menu.main]]
	identifier = "contacto"
	name = "Contacto"
	title = "Contacto"
	url = "/contacto/"
	weight = 4
	[[menu.main]]
	identifier = "buscar"
	name = "Busqueda"
	title = "Busqueda"
	url = "/buscar/"
	weight = 3
	[[menu.main]]
	identifier = "Noticias"
	name = "Noticias"
	title = "Noticias"
	url = "/posts/"
	weight = 2
	 [[menu.main]]
	identifier = "Historia"
	name = "Historia"
	title = "Historia"
	url = "/historia/"
	weight = 1

[params]
    featured_image="/img/apple.png"
	twitter = "https://twitter.com/apple?lang=es"